import { asset } from "@/src/lib/assets";
import type { Product, ProductFilter, SortOption } from "./ProductGrid.types";

export const products: Product[] = [
  {
    id: "hydraglass-pads",
    name: "HydraGlass™ Pads",
    price: 59,
    image: asset("/assets/waldor/product01.png"),
    secondImage: asset("/assets/waldor/product01_secondImage.png"),
    imageAlt: "HydraGlass Pads",
    category: "skin-care",
    href: "https://www.waldor.skin/products/hydraglass%E2%84%A2-longevity-pads?variant=54047116427528",
  },
  {
    id: "exosome-peptide-serum",
    name: "Exosome Peptide Stem Cell Serum 5ml",
    price: 99,
    image: asset("/assets/waldor/product02.png"),
    secondImage: asset("/assets/waldor/product02_secondImage.png"),
    imageAlt: "Exosome Peptide Stem Cell Serum 5ml",
    category: "skin-care",
    href: "https://www.waldor.skin/products/exosome-peptide-stem-cell-serum-5ml?variant=54047107842312",
    badge: "BESTSELLER",
  },
  {
    id: "hydraglass-collection",
    name: "HydraGlass™ Collection",
    price: 159,
    image: asset("/assets/waldor/product03.png"),
    secondImage: asset("/assets/waldor/product03_secondImage.png"),
    imageAlt: "HydraGlass Collection",
    category: "skin-care",
    href: "https://www.waldor.skin/products/korean-hydraglass%E2%84%A2-collection?variant=53383412842760",
    badge: "SET",
  },
  {
    id: "hydraglass-cream",
    name: "HydraGlass™ Cream",
    price: 59,
    image: asset("/assets/waldor/product04.png"),
    secondImage: asset("/assets/waldor/product04_secondImage.png"),
    imageAlt: "HydraGlass Cream",
    category: "skin-care",
    href: "https://www.waldor.skin/products/hydraglass%E2%84%A2-cream?variant=53374587961608",
  },
  {
    id: "hydraglass-serum",
    name: "HydraGlass™ Serum",
    price: 69,
    image: asset("/assets/waldor/product05.png"),
    secondImage: asset("/assets/waldor/product05_secondImage.png"),
    imageAlt: "HydraGlass Serum",
    category: "skin-care",
    href: "https://www.waldor.skin/products/hydraglass%E2%84%A2-serum?variant=53374495850760",
  },
  {
    id: "hydraglass-eye-lift-cream",
    name: "HydraGlass™ Eye Lift Cream",
    price: 89,
    image: asset("/assets/waldor/product06.png"),
    secondImage: asset("/assets/waldor/product06_secondImage.png"),
    imageAlt: "HydraGlass Eye Lift Cream",
    category: "skin-care",
    href: "https://www.waldor.skin/products/hydraglass%E2%84%A2-eye-lift-cream?variant=53374448861448",
  },
  {
    id: "hydraglass-cleanser",
    name: "HydraGlass™ Cleanser",
    price: 39,
    image: asset("/assets/waldor/product07.png"),
    secondImage: asset("/assets/waldor/product07_secondImage.png"),
    imageAlt: "HydraGlass Cleanser",
    category: "skin-care",
    href: "https://www.waldor.skin/products/hydraglass-cleanser?variant=53306421313800",
  },
  {
    id: "microneedle-longevity-cream",
    name: "Microneedle Longevity Cream",
    price: 89,
    image: asset("/assets/waldor/product08.png"),
    secondImage: asset("/assets/waldor/product08_secondImage.png"),
    imageAlt: "Microneedle Longevity Cream",
    category: "skin-care",
    href: "https://www.waldor.skin/products/microneedle-longevity-bottle?variant=53297631854856",
  },
  {
    id: "glow-facial-mask",
    name: "GLOW Facial Mask",
    price: 10,
    image: asset("/assets/waldor/product09.png"),
    secondImage: asset("/assets/waldor/product09_secondImage.png"),
    imageAlt: "GLOW Facial Mask",
    category: "skin-care",
    href: "https://www.waldor.skin/products/glow-facial-mask?variant=54590813405448",
  },
  {
    id: "lift-facial-mask",
    name: "Lift Facial Mask",
    price: 10,
    image: asset("/assets/waldor/product10.png"),
    secondImage: asset("/assets/waldor/product10_secondImage.png"),
    imageAlt: "Lift Facial Mask",
    category: "skin-care",
    href: "https://www.waldor.skin/products/lift-facial-mask?variant=54592956170504",
  },
];

export const filterTabs: { label: string; value: ProductFilter }[] = [
  { label: "All", value: "all" },
  { label: "Skin Care", value: "skin-care" },
  { label: "Merch", value: "merch" },
];

export const sortOptions: { label: string; value: SortOption }[] = [
  { label: "Featured", value: "featured" },
  { label: "Price: Low to High", value: "price-asc" },
  { label: "Price: High to Low", value: "price-desc" },
  { label: "Name: A to Z", value: "name-asc" },
];
